name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    pr-mode: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          pr-mode: false
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.1.1
